version: 2

build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10

conda:
  environment: .readthedocs_env.yml

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Don't build any extra formats
formats: []

sphinx:
  configuration: docs/source/conf.py
