# Deployment workflows, run when all CI tests pass on the `master` or `rc
# branches. NB: right now we do nothing on `master`! (But we need a dummy job to
# keep Pipelines happy.) That could change.

parameters:
  - name: isMainDev
    type: boolean
    default: false
  - name: isRelease
    type: boolean
    default: false

jobs:

- ${{ if parameters.isMainDev }}:
  - job: dummy_setup_only
    pool:
      vmImage: ubuntu-latest
    steps:
    - template: azure-job-setup.yml

- ${{ if parameters.isRelease }}:
  - job: branch_and_tag
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Deployment Credentials
    steps:
    - template: azure-job-setup.yml
      parameters:
        setupCranko: true
        setupGit: true
    - bash: |
        set -xeou pipefail
        cranko release-workflow tag
        git push --tags origin release:release
      displayName: Tag and push
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)

  - job: github_releases
    dependsOn: branch_and_tag # otherwise, GitHub creates the tag itself
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Deployment Credentials
    steps:
    - template: azure-job-setup.yml
      parameters:
        setupCranko: true
        setupGit: true
    - bash: |
        set -xeou pipefail
        cranko github create-releases
      displayName: Create GitHub releases
      env:
        GITHUB_TOKEN: $(GITHUB_TOKEN)

  - job: python_publish
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Deployment Credentials
    steps:
    - template: azure-job-setup.yml
      parameters:
        setupBuild: true
        setupCranko: true
    - bash: |
        set -eo pipefail  # no -u to work around Conda activation bug (2021 August)
        source activate-conda.sh
        set -x
        conda install -y twine

        cranko python install-token

        # If we ever become a monorepo, we'll need to figure out how to make sure
        # that we only upload the proper packages.
        if cranko show if-released --exit-code pwkit ; then
          twine upload $BASH_WORKSPACE/sdist/*.tar.gz
        fi
      displayName: Publish PyPI releases
      env:
        PYPI_TOKEN: $(PYPI_TOKEN)

  - job: zenodo_publish
    pool:
      vmImage: ubuntu-latest
    variables:
    - group: Deployment Credentials

    steps:
    - template: azure-job-setup.yml
      parameters:
        setupCranko: true

    - bash: cranko zenodo upload-artifacts --metadata=ci/zenodo.json5 $BASH_WORKSPACE/sdist/*.tar.gz
      displayName: Upload source tarball
      env:
        ZENODO_TOKEN: $(ZENODO_TOKEN)

    - bash: cranko zenodo publish --metadata=ci/zenodo.json5
      displayName: Publish to Zenodo
      env:
        ZENODO_TOKEN: $(ZENODO_TOKEN)
